"""Stable, platform-neutral contracts used by DS5Forge."""

from .errors import (
    CapabilityUnavailableError,
    ConfigValidationError,
    ControllerUnavailableError,
    DS5ForgeError,
    ErrorCode,
    PlatformUnavailableError,
    ProfileInvalidError,
)
from .events import EventEnvelope, EventType
from .models import (
    AdaptiveTriggerEffect,
    AudioSnapshot,
    BatterySnapshot,
    CapabilityAvailability,
    ConnectionState,
    ControllerCapabilities,
    ControllerIdentity,
    ControllerInput,
    ControllerProfile,
    ControllerReading,
    ControllerTelemetry,
    ErrorSnapshot,
    GestureConfig,
    HapticsTestRun,
    HealthSnapshot,
    LightbarState,
    MotorSnapshot,
    RuntimeSnapshot,
    StickCalibration,
    StickTelemetry,
    TouchPoint,
    TriggerMode,
    TriggerPreviewState,
    TriggerState,
    normalize_controller_input,
    normalize_controller_reading,
)

__all__ = [
    "AudioSnapshot",
    "AdaptiveTriggerEffect",
    "BatterySnapshot",
    "CapabilityUnavailableError",
    "CapabilityAvailability",
    "ConfigValidationError",
    "ConnectionState",
    "ControllerCapabilities",
    "ControllerIdentity",
    "ControllerInput",
    "ControllerProfile",
    "ControllerReading",
    "ControllerUnavailableError",
    "ControllerTelemetry",
    "DS5ForgeError",
    "ErrorCode",
    "ErrorSnapshot",
    "EventEnvelope",
    "EventType",
    "GestureConfig",
    "HealthSnapshot",
    "HapticsTestRun",
    "LightbarState",
    "MotorSnapshot",
    "PlatformUnavailableError",
    "ProfileInvalidError",
    "RuntimeSnapshot",
    "StickCalibration",
    "StickTelemetry",
    "TouchPoint",
    "TriggerMode",
    "TriggerPreviewState",
    "TriggerState",
    "normalize_controller_input",
    "normalize_controller_reading",
]
